# Generated by Django 5.1.4 on 2025-01-11 19:46

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced_ordered_date_alter_orderplaced_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
            preserve_default=False,
        ),
    ]